CREATE TABLE PLACE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    COUNTRY VARCHAR(64) NOT NULL,
    CITY VARCHAR(64) NOT NULL,
    ADDRESS VARCHAR(64) NOT NULL,
    NAME VARCHAR(64) NOT NULL,
    LAT DECIMAL NOT NULL,
    LNG DECIMAL NOT NULL,
    BAG_CAPACITY INT NOT NULL,
    PRICE DECIMAL(6,2) NOT NULL,
    TIME_OPEN INT NOT NULL,
    TIME_CLOSE INT NOT NULL,
    RATING INT NOT NULL,
    DESCRIPTION VARCHAR(256) NOT NULL
);


CREATE TABLE CUSTOMER(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
);


CREATE TABLE BOOKING(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    PLACE_ID BIGINT NOT NULL,
    BAG_AMOUNT INT,
    DATE_START DATE,
    DATE_END DATE,
);